### ISSUE TITLE
There is no way to calculate the topological charge

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#1]
This would be useful, especially for skyrmions

**Comment by GPMueller** [comment]
Added function stub in 80eb6bf869f352a8657c71beae131f11c0772dad

**Comment by SpiritSuperUser** [comment]
this would be a great feature! one could also make a colormap for the vizualization which is defined by the local topological charge!

**Comment by GPMueller** [comment]
That is a good idea! And once the charge calculation is in place it would be quite easy to do.

**Comment by GPMueller** [comment]
If I understand correctly, to calculate the topological charge, we simply need to check that the system is 2D and calculate the surface angle between triples of spins, where the triples should tile the 2D plane.
Related to #224 and #283, QHull could be used to extract the Delaunay triangulation.

**Comment by GPMueller** [comment]
Since cf99c840f63e5154b61a97a4f8dbb2d1ab6fbae0, this could be calculated using the Delaunay triangulation of the lattice.

**Comment by GPMueller** [comment]
Finally implemented with a84d361d084b5a25f099cd2e5a784e82061a820f.
Note: periodical boundaries could give incorrect results, I am not 100% sure here.
