### ISSUE TITLE
Multiple Isosurfaces

### ISSUE THREAD

**Issue by n-s-kiselev** [spirit-code/spirit#137]
This would be a very nice feature:
![image](https://cloud.githubusercontent.com/assets/22953999/23559926/ebabeac0-0038-11e7-9769-7272c7a51159.png)

**Comment by GPMueller** [comment]
Implemented in 17806365144822fe0be063cccb7c4cc69e870b03.
An arbitrary number of isosurfaces can be inserted. An example with two isosurfaces:
![2017-03-06_13-57-56_screenshot_1](https://cloud.githubusercontent.com/assets/20167491/23611364/33e20b54-0277-11e7-976e-4b912eda8a49.jpg)
