### ISSUE TITLE
Core: API functions should test for invalid input (e.g. non-normalized vectors)

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#164]
Setting a zero vector for example may cause crashes in some cases.
Currently this is checked in the UI - this should not be necessary!

**Comment by GPMueller** [comment]
Related to #27.
In this case, however, the code should not exit but write a corresponding Log message.

**Comment by smavros** [comment]
This is addressed with #281

**Comment by GPMueller** [comment]
Merged with 23467a67aae73c3fd5cac95c4d0342e2efa0bb1b.
