### ISSUE TITLE
Write Spirit version as comment into output files

### ISSUE THREAD

**Issue by broeder-j** [spirit-code/spirit#166]
This would be useful for history checking.

**Comment by GPMueller** [comment]
Basic requirements for this were implemented in PR #319 with commit 10037fb and merged with 0b9db5512500163d35af449057c9133a3b010a89.
The version is already written into OVF files, but not yet into regular output.

**Comment by GPMueller** [comment]
The version tag on other file formats was also implemented on PR #319 (with 9f8137a786950157fe67319920e52b19db285cbe).
