### ISSUE TITLE
Core: spin current with non-SIB optimizers creates problems

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#198]
- the current has no effect, but convergence is deactivated
- no message is printed to warn the user

**Comment by GPMueller** [comment]
Resolving #182 would also solve this problem, as the STT term etc. would be added to the force in any of the Optimizers... This may lead to unphysical results but maybe this is preferable w.r.t. unexpected non-convergence etc.

**Comment by SpiritSuperUser** [comment]
> This may lead to unphysical results but maybe this is preferable w.r.t. unexpected non-convergence etc.

if the choice is between "_unphysical results_" or physical results with an "_unexpected non-convergence etc._" this is **not a choice**! The first option is **unworthy of discussion**!

**Comment by GPMueller** [comment]
You are of course right. I meant that the user would need to ensure that what he does makes sense. Using an Optimizer with zero damping for example will just give endlessly propagating spin waves after some time - this is unphysical but maybe of interest for some special case.

**Comment by GPMueller** [comment]
Since 135cc1fcb33f1452a65f2c44cd0aa3d36a3442f9 on `feature-refactor-method`, this could be fixed by letting the `Iteration` function decide what to put into the force which is used for the `max_abs_component` calculation. When using temperature or spin current, the `virtual force` will inherently be nonzero and this problem would be solved cleanly.

**Comment by GPMueller** [comment]
Merged `feature-refactor-method` into `develop` with 8402598137b1e30c01343542fa0d412cec59b340.

**Comment by GPMueller** [comment]
Fixed with 4305404cbfbde723deb63467060bfd4e940cf603.
