### ISSUE TITLE
UI-QT: GNEB climbing/falling images

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#211]
it would be great, if a GNEB calculation could automatically define, which images are climbing/falling images (by comparing energies of neighboring images). This could be done once via a button/function but also a mode allowing this to be done automatically after every X iterations might be useful

**Comment by GPMueller** [comment]
The automatic functionality I will likely not implement, as I consider it a bit too specialized.

**Comment by SpiritSuperUser** [comment]
👎

**Comment by SpiritSuperUser** [comment]
I would like to highlight, that my suggestion was not ui related, as the new topic set by @GPMueller suggests

**Comment by GPMueller** [comment]
> This could be done once via a button/function

I renamed it because I don't think I will add it as a non-UI automatic feature.

**Comment by GPMueller** [comment]
Implemented an API function and a corresponding button in UI-QT with d8bba91cb7ab9a67a297acdf0d40b97958de0131.

@SpiritSuperUser A python wrapper could be added for this function if you think this makes sense (it would still have to be called manually, but you wouldn't have to set image types manually.

**Comment by GPMueller** [comment]
C API function is called `Parameters_Set_GNEB_Image_Type_Automatically`.
Python binding added with 26603fb63765ba1d39ed24541b8e071de3eccc24: `parameters.Set_GNEB_Image_Type_Automatically`.
