### ISSUE TITLE
ui layout

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#213]
in my opinion it would be better to be able to have more than one subcategory within the tabs (eg. _Settings_ **AND** _Localised States_ within the _configurations_ tab ) open at a time. to avoid too lengthy output, one could split the subcategories further into sub-sub-categories (eg. _skyrmion_ and _hopfion_ in the localised stated categort) which are again separately expandable

**Comment by GPMueller** [comment]
The link you sent may indeed be the right way: http://stackoverflow.com/a/11099200/4069571

**Comment by GPMueller** [comment]
Improved layouting is being implemented for ui-imgui on the `feature-imgui` branch. Concerning spin configurations setters, this is the current look:
![grafik](https://user-images.githubusercontent.com/20167491/103468235-331d8c00-4d57-11eb-96ac-56504b8149c1.png)

Currently, only "Settings" is collapsible, but I expect with a growing feature-set more will be placed into collapsible regions.
