### ISSUE TITLE
Documentation: improve core/docs/Python_API.md 

### ISSUE THREAD

**Issue by smavros** [spirit-code/spirit#216]
Add:
- explanation for State->Chain->Image structure (probably ASCII art)
- description column at System table
- example and details for State initialization
- example and details for Chain manipulation

Remove:
- Set/Get_LLG/GNEB_N_Iterations_Log functions

**Comment by GPMueller** [comment]
This will be adressed in PR #218.

**Comment by GPMueller** [comment]
Merged with e2edd0dd86703e274f4ffce35b9420e855b789b4.
