### ISSUE TITLE
Core: fix Python parameters bindings

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#225]
The N_Iterations API has been changed, the Python bindings have not been updated.

**Comment by GPMueller** [comment]
Coming with PR #218.

**Comment by smavros** [comment]
Changes at Python API parameter.py
- Get/Set_LLG/GNEB_N_Iterations_Log() have been removed.
- Get/Set_LLG/GNEB_N_iterations() have been properly modified.

**Comment by GPMueller** [comment]
Merged PR #218 with e2edd0dd86703e274f4ffce35b9420e855b789b4.
