### ISSUE TITLE
Python Bindings: consistently wrap arguments with ctypes

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#226]
By wrapping arguments into ctypes, one can avoid e.g. passing a float into a library function which takes an int. One will then get a somewhat clearer message: `TypeError: int expected instead of float` instead of `ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: wrong type`.

**Comment by smavros** [comment]
For future changes in the API the functions' arguments should be wrapped in ctypes like
` _Jump_To_Image( ctypes.c_void_p( p_state ), ctypes.c_int( idx_image ), ctypes.c_int( idx_chain ) )`
in order to get more meaningful Errors.

**Comment by GPMueller** [comment]
Implemented with PR #303 and merged with 0d241a333c9626253a73be2c2a9a9e962d9e3e4d.
