### ISSUE TITLE
Core: SingleShot() function is meaningless

### ISSUE THREAD

**Issue by smavros** [spirit-code/spirit#231]
`SingleShot()` and `PlayPause()` at simulation.py have same arguments and probably same functionality. `SingleShot()` should be removed or modified in a meaningful way that defines its functionality and its differences in contrast to `PlayPause()`

**Comment by GPMueller** [comment]
This function is incorrectly specified in the core *and* the python bindings.

**Comment by GPMueller** [comment]
Maybe just add a `SingleShot` function to `Method`?
It could simply call the initialization functions, one iteration and then finalization function, without printing lots of messages. Maybe take a parameter 'log_messages'?

**Comment by GPMueller** [comment]
Fixed somewhere... In any case the unit tests merged with 491ce2f495b239bd62b6e7b367e27fdcbe16699c use the `SingleShot` function in a meaningful way, so I'm closing this issue.
