### ISSUE TITLE
BUG: Core Chain_Delete_Image() effect when deleting non existing image

### ISSUE THREAD

**Issue by smavros** [spirit-code/spirit#232]
Descritpion of the problem
=====================
When `Chain_Delete_Image()` is called for a non existing images it deletes one unidentified image of the chain. It is not easy to see which image is deleted:
- the last one when the index is greater than the largest existing index?
- the 0th one when the index is lower than 0
- the active image 

Steps to reproduce
------------------------
1. Setup a chain with at least two images. They will have indices 0 and 1. 
2. `Chain_Get_NOI()` is 2
3. Try delete an image with index >= 2 or index < 0
4. `Chain_Get_NOI()` is 1. 

Expected behaviour
-------------------------
When `Chain_Delete_Image()` is given an index which does not corresponds to any image:
1. It must not affect the pre-existing images (NOI must be unchanged) 
2. It should raise a meaningful `[Warning]` in the log

**Comment by smavros** [comment]
After fix the tests at chain.py must be modified. Now they are passing successful because they are testing for the erroneous behaviour and not the expected as it is described in this issue.

**Comment by GPMueller** [comment]
Merged the fix with with 23467a67aae73c3fd5cac95c4d0342e2efa0bb1b.
