### ISSUE TITLE
Core: calculation of mean

### ISSUE THREAD

**Issue by smavros** [spirit-code/spirit#238]
It is not sure what is the proper way to calculate mean of vectorfields. We should check the performance by profiling.

**Comment by GPMueller** [comment]
We should also check which way is better for numerical precision of the final result.

**Comment by GPMueller** [comment]
In the end the OpenMP parallelization dictates we use the "sum and divide" method or one would have to write a proper specialized reduction kernel and I doubt it's worth the effort.
Done with 07b8d90d0e0f1174f83e878247e41c5dcdfb8215 on feature-openmp.

**Comment by GPMueller** [comment]
Merged into `develop` with 03a38cf4c0cd730566449320a0a012b2feea4178.

Note that first summing and then dividing gives better precision than dividing all summands. This gave a precision problems on large enough systems when `float` was used as data type.
