### ISSUE TITLE
QHull is built twice

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#24]
This is due to the need for two build targets, but this can be circumvented somehow.

**Comment by FlorianRhiem** [comment]
You can build it once and then use the built libraries as imported libraries. See [VFRendering/CMakeLists.txt](https://github.com/FlorianRhiem/VFRendering/blob/master/CMakeLists.txt#L7).

**Comment by GPMueller** [comment]
Fixed in 21bb197be80cf5e95a2ece
