### ISSUE TITLE
Core: timestep in LLG Method has to be divided by 1+damping^2

### ISSUE THREAD

**Issue by Disselkamp** [spirit-code/spirit#245]
https://github.com/spirit-code/spirit/blob/4103790b797ec7d4d8720a789d21d97cac88327d/core/src/utility/IO_Configparser.cpp#L346

**Comment by GPMueller** [comment]
The scaling of the time step should be done in the Optimizer. Otherwise, confusion, especially with respect to prefactors, may arise.

**Comment by GPMueller** [comment]
Fixed with 36a41fd463eda2547fef6e2dae9a474952041cae.
