### ISSUE TITLE
energy plot accuracy problem?

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#247]
it looks like the the interpolated line does not go through the center of the points. I guess this is an accuracy problem of the calculated energies (of the points/images), am I right? looks a bit confusing, but I guess than it is not solvable...

<img width="406" alt="screen shot 2017-06-08 at 10 42 56" src="https://user-images.githubusercontent.com/28620252/26921335-039efb96-4c3c-11e7-9179-3aabe159f5da.png">

**Comment by GPMueller** [comment]
If you save the energies to file and plot them separately, this problem does not appear, right?

**Comment by SpiritSuperUser** [comment]
you are right. then I retract my last statement and claim that it should be solvable

**Comment by GPMueller** [comment]
I don't know what could be causing this, it seems it is not a timing problem (interpolated energies being calculated at a different time from the discrete points)...

**Comment by SpiritSuperUser** [comment]
Not directly related I guess but also an accuracy problem: 
Too small energy differences can not be visualized in the energy plot. This is most probably a result of the lower accuracy of the plotted data than the real calculated data. Maybe one could solve this by the following feature request: Show energies with respect to first or last image or set the image with the lowest energy to zero. This could be a dropdown menu where one could choose between "total" "relative to first/last" or "relative to minimum". By this, we deal only with small numbers and not small differences with respect to a huge total energy...

**Comment by GPMueller** [comment]
This issue should be solved with the plotting implementation on the `feature-imgui` branch.
