### ISSUE TITLE
feature request: homogeneous transition between first and last image per button

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#249]
It would be way more convenient, if one could just press a button and the transition is done between the first and the last image of the chain. it is annoying that one needs to type in at least the number of the last image, as the value is by default set to 1...

I would recommend to add an additional button which is purely there to do this transition between first and last image

**Comment by GPMueller** [comment]
Implemented with 132ed9f7325b005b29124243eeacbdabdfe2650c.
