### ISSUE TITLE
UI-QT: improve chart refresh

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#262]
Instead of removing and re-adding series, it should be way better to use the `QXYSeries::replace` function (https://doc.qt.io/qt-5/qxyseries.html#replace-5).
However, it is unclear to me how to then refresh the chart. The `replace` function does not trigger the same update which `addSeries` does.

#261 could be related to the periodic add and remove.

**Comment by GPMueller** [comment]
Implemented with deeb185551ee304dc401259a588a4a998cd66370. It seems #261 is indeed resolved by this.

**Comment by adibhannachi** [comment]
Totally agree,it's the best solution .
For your inforamtions until now ,a  memory leak caused by QXYSeries:: remove.
