### ISSUE TITLE
API: Proper termination of the application

### ISSUE THREAD

**Issue by smavros** [spirit-code/spirit#282]
During the handling of the exceptions thrown by the core/API functions we may want to terminate the application (e.g. in `Exception::Division_by_zero` ). The right way would be to have a `try{ ... } catch{ ... }` in our entry point since any uncaught exceptions may cause an abnormal termination. I am not sure if it is ok to just append the message regarding the exception to the Log by `Log.Append_to_File()` or `Log.Dump_to_File()` and then call `std::exit`.

Related answer on SO: https://stackoverflow.com/a/30251056

**Comment by GPMueller** [comment]
The API should not throw exceptions, as they are defined as a C interface, not C++. This requires us to catch all exceptions at the latest in the API layer and exit the code if the exception cannot be handled.
