### ISSUE TITLE
UI-QT: surface renderer does not update correctly when other visualisation settings change

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#285]
e.g. changing camera projection will result in the surface no longer being drawn until an update is triggered, e.g. by a change of the spin configuration.

**Comment by GPMueller** [comment]
@SpiritSuperUser please check if you can reproduce this on the most recent `develop` version, I currently cannot reproduce this.

**Comment by SpiritSuperUser** [comment]
yes, I still face this bug..

I'm on the newest `develop` version:
commit 7ee4932e0ad755b7eac91285e9abf3baaef749de
Author: Gideon <g.mueller@fz-juelich.de>
Date:   Mon Sep 4 21:02:07 2017 +0200

**Comment by SpiritSuperUser** [comment]
it happens in many cases:

- changing projection
- switching on/off mini view
- changing position of mini view
- switching on/off coordinate cross 
- changing position of coordinate cross
- switching on/off the boundary box
- switching ON (off works, maybe this gives a hint..) arrows

**Comment by SpiritSuperUser** [comment]
even switching off the surface mode and switching it back on does not show the surface again until one triggers a change of the spin configuration...
so the first "switching on" procedure works, after that the surface is only triggered by spin configuration changes

**Comment by GPMueller** [comment]
In the meantime, issues #374 and #375 were resolved and thereby possibly also this problem.
Please try again if this still persists on the current `develop` version.

This may even be related to  #329, but I don't believe so.

**Comment by GPMueller** [comment]
Closing, as the issue seems resolved.
