### ISSUE TITLE
UI-QT: Termination due to floating point exception when 'log steps' is set to zero

### ISSUE THREAD

**Issue by smavros** [spirit-code/spirit#301]
### Reproduce

* start Spirit with any input file
* choose LLG method and any of the provided solvers
* in the `output` panel set `log steps` to zero or leave it unset
* `Play` to start simulation
* Termination due to `Floating point exception(core dumped)`

### Expected Behavior

If the user does not want any output in between the `Initial` and `Final` iteration he/she can uncheck `Any` in the `output` panel. In case that `log steps` is set to zero it would be better to
* automatically unset `Any` choice 
* set `output` value to `1` so we would avoid division by zero

_Note:_ It would be good idea to also guard for negative values in the UI fields even though `0`-value cases would be more likely to occur.

**Comment by GPMueller** [comment]
Fixed with 7ee4932e0ad755b7eac91285e9abf3baaef749de.
