### ISSUE TITLE
feature request: load multiple SpinConf files at once

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#314]
In my opinion it would be great to load multiple SpinConf files at once. Up to know one can just choose one file at a time. Wouldn't it be great to select multiple files and they are read in similar to a SpinChain?

**Comment by GPMueller** [comment]
Implemented with 02c341d5df3b93be865de64994d0f7bb55ccaeaf.

Note that the order of the read images seems to always be the same as in the file browser. Changing QT's default behaviour would be a lot of work and not worth the effort imho.
