### ISSUE TITLE
QT message at start

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#315]
I got this message when starting spirit. No idea whether it had any negative effects but anyway, just to let you know:

> qt.qpa.cocoa.window: Window position outside any known screen, using primary screen

**Comment by GPMueller** [comment]
Does this still appear or was this a one-time occurrence?

**Comment by SpiritSuperUser** [comment]
I did not see this message since then

**Comment by GPMueller** [comment]
Then it is likely due to either some problem with the saved window sizes between code versions or a change from multi-screen to single-screen or something like this. In any case it shouldn't be harmful.
