### ISSUE TITLE
ui layout buggy

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#322]
well, I guess an image says it all:

<img width="404" alt="screen shot 2017-10-06 at 09 16 24" src="https://user-images.githubusercontent.com/28620252/31267154-675e226c-aa77-11e7-962b-8fa9b0f10853.png">

running on a mac

**Comment by GPMueller** [comment]
Fixed with 1c04de22bd724ede5e21f040f7589c51908596fc.
