### ISSUE TITLE
feature request: forces per image

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#324]
during a GNEB calculation it would be great not only to see the maximum force of all images but also the current maximum force of each image (well, maybe always just the total maximum and the maximum of the currently visible image, otherwise it gets a bit messy :) )

**Comment by GPMueller** [comment]
Implemented with 4f623c1ec2d7c335ccc17844e9220599a24cbea2.
Note the statusbar font is now monospace, so it should be easier to keep an eye on the numbers while they change.
