### ISSUE TITLE
UI-CPP: color map is changed when boundary conditions are changed?

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#329]
This was reported by @SpiritSuperUser.
> When a different colormap is selected for the arrows and boundary conditions are changed, the colormap is switched back to general. It may also be that other parameters are re-set (LLG etc.) when switching between images with different boundary conditions.

This may be caused by the update of checkboxes etc. triggering a new signal, which in turn calls API functions to set parameters.

**Comment by GPMueller** [comment]
This is due to the way Spirit uses VFRendering and the way `VFRendering::GlyphRenderer::updateShaderProgram` uses `VFRendering::View::Options` instead of having `VFRendering::GlyphRenderer::Options`.

This needs to be discussed with @FlorianRhiem, how this could/should be changed. I suppose that it's not necessary to give all the different `Renderer`s their own redundant `Option`s, but I don't see how the classes could avoid using the `View`s global `Options`.

Since one can e.g. `renderer_arrows->setOption<VFRendering::View::Option::COLORMAP_IMPLEMENTATION>(colormap_implementation);`, i.e. set `Option`s individually, I believe the expected behaviour would be that this option is retained, even when `updateShaderProgram` is called.

**Comment by GPMueller** [comment]
Specifically, the problem comes from https://github.com/FlorianRhiem/VFRendering/blob/master/src/View.cxx#L158
The `CombinedRenderer` is re-created when renderer settings change, then `View::renderers` is called, causing `updateOptions(options())` to be called, i.e. using the `options()` of the `View`.

To me this would make sense if the `Renderer`s would not already initialize their options from the `View`s options on creation. Maybe this can just be skipped?

**Comment by FlorianRhiem** [comment]
I have [added an optional parameter `update_renderer_options`](https://github.com/FlorianRhiem/VFRendering/commit/7defb0098f8f20131953591c3ffe390badf5d8f9) to `View::renderers()` that should make this issue easier to circumvent. You will need to update to [VFRendering 0.11.0](https://github.com/FlorianRhiem/VFRendering/releases/tag/v0.11.0).

**Comment by GPMueller** [comment]
Thanks!

Updated to VFRendering 0.11.0 with a5f70edcd531f0fe9c2b9e66c3c72f6a92ef14cb.
Added corresponding code to `SpinWidget` with f49cda980a44a45f50de2952f7359a1d960208ac, which fixes the issue.
