### ISSUE TITLE
Spirit CSV format - Implementation missing

### ISSUE THREAD

**Issue by smavros** [spirit-code/spirit#336]
# Writing

API function `IO_Image_Write()` is calling `IO::Write_Spin_Configuration()` without any argument specifying the Spirit file format (for OVF is a call to a different function `IO::Save_To_OVF()`). The implementation of `IO::Write_Spin_Configuration()` seems to write only whitespace-seperated data.

# Reading

API function `IO_Image_Read()` is calling `IO::Read_Spin_Configuration()` with file format as argument but the implementation is changing only for `CSV_POS_SPIN` file format.

**Comment by GPMueller** [comment]
Fix has been merged with 4ae862a374f6b2be7d62bfc2c065397962af5fa5.
