### ISSUE TITLE
File IO: SIGSEGV from IO::Write_Image_Energy_per_Spin()

### ISSUE THREAD

**Issue by smavros** [spirit-code/spirit#342]
prior to PR #319 the function was named `Write_System_Energy_per_Spin()`

# Problem

The function `Write_Image_Energy_per_Spin()` in io/Datawrite.cpp will give a `SIGSEGV` in case that it is called before the energies are calculated (before the `Update_Energy_Contributions()` is called at least once). The signal will raised by

```c++
for (auto& contribution : contributions_spins) E_spin += contribution.second[ispin];
```
since `contribution` would be an empty `std::pair<std::string, scalarfield>`

# Solution 

A check on the `contributions_spins.size()` should be done, probably by `Write_System_Energy_per_Spin()`.

**Comment by GPMueller** [comment]
The underlying problem is that a data consistency mechanism is missing.
Certain data (as in this example) is not calculated when the code starts, other is not updated automatically.

Probably the best approach would be to implement lazy evaluation for certain quantities. The container which keeps the data would need e.g. integers to keep track of changes.

**Comment by GPMueller** [comment]
I don't recall when, but this should be fixed by now. `Hamiltonian_Heisenberg::Update_Energy_Contributions` is called at least once: upon construction of the Hamiltonian and the `Hamiltonian_Heisenberg::Energy_Contributions_per_Spin` function now performs a check of the passed `contributions`:
```C++
if( contributions.size() != this->energy_contributions_per_spin.size() )
{
contributions = this->energy_contributions_per_spin;
}

int nos = spins.size();
for( auto& contrib : contributions )
{
// Allocate if not already allocated
if (contrib.second.size() != nos) contrib.second = scalarfield(nos, 0);
// Otherwise set to zero
else Vectormath::fill(contrib.second, 0);
}
```
