### ISSUE TITLE
UI-QT: Glitch on Save/Load window

### ISSUE THREAD

**Issue by smavros** [spirit-code/spirit#397]
Under Linux:
If a simulation is running on an Image the UI window of any IO operation (save/load for image, modes, chain) is empty. It is not blank but see-through. Just the frame of the window is drawn.

**Comment by GPMueller** [comment]
Please specify the version of desktop you are running - I cannot reproduce this on KDE 5.

**Comment by smavros** [comment]
Fedora 27
XFCE 4.12
Qt version 5.9.4.

**Comment by GPMueller** [comment]
I believe this is a problem of Qt in this specific case. When a simulation is running, the OpenGL visualisation is continuously redrawn, which apparently interferes with the drawing of the "Save"/"Load" window.

As far as I can tell it is not a problem of Spirit itself, so I will close this issue.
