### ISSUE TITLE
VFRendering: Coordinate cross in orthographic projection

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#40]
The **orthographic** projection of the coordinate cross seems to change with the proportions of the window (in contrast to the other renderers). Two examples for non-quadratic windows:
<img width="111" alt="screen shot 2016-12-23 at 12 04 36" src="https://cloud.githubusercontent.com/assets/20167491/21452604/6aafd4e8-c908-11e6-88ba-448cdaeeb177.png">
<img width="72" alt="screen shot 2016-12-23 at 12 05 03" src="https://cloud.githubusercontent.com/assets/20167491/21452606/70e62056-c908-11e6-9f2e-064956c970aa.png">

**Comment by FlorianRhiem** [comment]
Proper handling of the aspect ratio for the orthographic projection in the CoordinateSystemRenderer was added in 0dcd0da2bbb4c82d08d35b67fc1d9b4cf22d8f56.
