### ISSUE TITLE
Logfile: implementation not finished i guess

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#400]
I will add here stuff whenever I see a case where the output to the log looks weird

new noi value is not written out, just the blank message:
>  [ INFO  ] [API ] [01] [14]  Inserted image after. NOI is now

**Comment by GPMueller** [comment]
Fixed with 4ae862a374f6b2be7d62bfc2c065397962af5fa5 (merge of PR #410).
