### ISSUE TITLE
Feature request: highlight max force image in plot

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#401]
During a GNEB calculation it would be nice to highlight the image on which the maximal force is acting at the moment. I would just take another color for the circle/triangle in the energy plot.

**Comment by GPMueller** [comment]
Unfortunately, this turns out to be harder to realise than I would have expected... The Qt charts API is very limited regarding the addition of single, specially styled points to the chart.

**Comment by GPMueller** [comment]
This should be reasonably easy to implement in ui-imgui on the `feature-imgui` branch, now that the plotting widget there has progressed a bit.

**Comment by GPMueller** [comment]
Implemented with 67b04c1bba04d35a052ef3e89d6fa5523efd1414 on branch `feature-imgui`.

**Comment by GPMueller** [comment]
![grafik](https://user-images.githubusercontent.com/20167491/123460990-c1791900-d5e8-11eb-8dc5-5b1219b13af5.png)

red is the current image, orange is the max. force image.
