### ISSUE TITLE
UI: camera can not be changed via the text-boxes

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#404]
camera can not be changed via the text-boxes anymore. the value is resettet to the current positions immediately.

**Comment by SpiritSuperUser** [comment]
the values in the boxes should only be updated when the camera in the main frame is changed and not every few milliseconds.

**Comment by GPMueller** [comment]
Fixed with fe53d02936051e5eb5945cd0312d0cccc06ab807.
The image index can now also be changed from the corresponding lineEdit.
