### ISSUE TITLE
UI: energy plot

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#405]
the white circles around the points in the plot might be quite nice to separate the dots from the line for visual purposes. However, when there are too many data points, they start to overlap and in the worst-case-scenario you only see the white boundaries of each point while the main body is overlapped by the next point. This is not really good since the background is white as well... ;)
maybe one should be able to toggle those white borders or maybe I just ran into an issue which will never really bother anyone again (GNEB calculations with hundrets of images...)

**Comment by SpiritSuperUser** [comment]
<img width="410" alt="screen shot 2018-03-21 at 15 32 47" src="https://user-images.githubusercontent.com/28620252/37715786-390f91a6-2d1d-11e8-8499-4ce2b4bdefa0.png">

**Comment by GPMueller** [comment]
With 5a98cc3cc1c64fe5228e02c32c64c18eec27c654:
- improved the visibility by reducing the size of markers and removing margins around the plot
- added checkbox whether to draw the markers

Unchecking the new checkbox (while using interpolated energies) turns this

<img width="378" alt="screen shot 2018-06-12 at 23 12 42" src="https://user-images.githubusercontent.com/20167491/41322051-6440b6c4-6e96-11e8-8fe1-729d3ee42a95.png">

into this

<img width="377" alt="screen shot 2018-06-12 at 23 12 52" src="https://user-images.githubusercontent.com/20167491/41322057-6a9c6234-6e96-11e8-9b20-1274554a3a4e.png">

And will solve your problem of the basically invisible line.

**Comment by SpiritSuperUser** [comment]
I'm not so sure how useful the version without markers really is. I somehow would have preferred to be able to toggle just/additionally the white borders.

btw., what was again the reason, why it seems like the lines are not connected to the center of the dots. In your example, all the dots are sitting slightly too high... From the energy scale I would say it can's be an accuracy problem...

**Comment by GPMueller** [comment]
What would be the benefit of having the markers, in contrast to how it is now? It will just create a very thick line. You might be able to still see climbing/falling indicators, but I think they would actually be completely blocked.

Unfortunately, I have not been able to figure out why the dots seem off-center.

**Comment by SpiritSuperUser** [comment]
well, one would still be able to see, how many images there are actually and how close they are to each other. 
And yes, I agree that the climbing/falling stuff would be some further information of interest which one would like to see. The issue of "being blocked" could be solved by reordering the dots such that the climbing and falling image triangles are plotted on top of (ie. later than) the circles of normal images. I'm not sure how easy this can be done, it's for sure doable since one could just plot different data sets: split the full data set in one for the normal images and one for the "special" ones.
