### ISSUE TITLE
IO: error messages per image

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#406]
Maybe it would be sufficient to throw error messages like

> Could not open ... to append to file

just once... I understand, that the append function is called per image, but I think it is an overkill to throw the error for each image, maybe one can just stop the writing procedure when the first image runs into the error

**Comment by GPMueller** [comment]
This has been fixed with the merge of PR #410 (4ae862a374f6b2be7d62bfc2c065397962af5fa5).
