### ISSUE TITLE
UI BUG: LLG parameters are set when one jumps to another image

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#407]
Every now and then, the LLG parameters are set when one jumps to other images by pressing and HOLDING the arrow key. This happens right now reproducible after about 5 images were scrolled through... If one keeps the key pressed, the image change requests are buffered, but after EACH image change, the parameters are set again. This, in combination with the other bug related to parameter sets (takes ages instead of milliseconds), is quite annoying.
A GNEB calculation is running at the moment and before that, the timestep was changed. somehow it looks like this timestep change is performed again during the image jumps.

**Comment by SpiritSuperUser** [comment]
correction: it also happens when one repeats the pressing of the arrow key with a too high frequency

**Comment by SpiritSuperUser** [comment]
correction2: now it happens every time when I jump to another image. Time to restart SPIRIT I guess :)

**Comment by GPMueller** [comment]
This should not happen in the IMGUI on the `feature-imgui` branch. This issue will be closes when the corresponding PR #583 is merged.
