### ISSUE TITLE
IO: Chain_Read if file does not exist

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#409]
somehow I think `io.Chain_Read` should throw an error message or at least a warning if the selected file does not exist...

**Comment by GPMueller** [comment]
A warning should be logged on the current version. What version are you using and what are your Log settings?

**Comment by GPMueller** [comment]
This has been fixed with 4ae862a374f6b2be7d62bfc2c065397962af5fa5 (merge of PR #410) and with e2ec42375dbee1ae75101d43599060275e993543, messages are now much more clear.
