### ISSUE TITLE
Pinning and geometry change do not work together

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#419]
if pinning is switched on, changing the geometry results in a huge mess, ie. it is not working.

preferred behavior if the geometry is changed:
- if boundaries are pinned, this pinning should be adapted to the new size, ie. the new boundaries should be pinned
- if single spins are pinned, those spins should remain pinned, ie. the index has to be adapted to the new dimensions

**Comment by GPMueller** [comment]
This should be implemented as soon as #393 is done.
The generic pinning should also be specified in translations instead of absolute indices, which would avoid further problems with pinning when changing geometry.

**Comment by GPMueller** [comment]
Implemented the translations-specified pinning (as well as defects) with 978682a18eb6d37fc4809bbae31b54339bc29260. They are therefore not influenced anymore by changes to the Geometry (at least `n_cells`).
