### ISSUE TITLE
Configurations API: position is not uniquely defined

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#449]
the positions are not uniquely defined in all functions.
setting a spin configuration (eg., `plus_z`), the _center_ of  the lattice is the origin while for `pin`, the _corner_ is the origin

**Comment by GPMueller** [comment]
Tried to fix this with 214d428aabeeb157c4134722c5413c909a739c79.
Note that API functions have changed slightly:
- `Configuration_Pin` -> `Configuration_Set_Pinned` (now also takes a bool)
- `Configuration_Atom_Type` -> `Configuration_Set_Atom_Type`
- `configuration.pin` -> `configuration.set_pinned` (now also takes a bool)
- `configuration.atom_type` -> `configuration.set_atom_type`

Also, you can now un-pin with right-click.
