### ISSUE TITLE
HTST: check force at beginning

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#450]
It would be useful if the forces are checked at the beginning of a HTST calculation. This would avoid long wrong calculations if the read-in images do not correspond to the minimum or the SP.

**Comment by GPMueller** [comment]
Implemented with 4f99c20d595ccbf83a01a32dbd76a2c9a4560546.
The threshold for convergence is set to `1e-8`, which should be usually enough.
