### ISSUE TITLE
HTST: SP with more than 1 negative EW

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#451]
while a stable SP can in principle have more than one negative eigenvalue, calculating the HTST prefactor does not make sense in this case. Right now, the eigenvalues for the minimum and the SP are calculated and then the prefactor calculation follows but results in a `nan`. To optimize computing time it would be best to calculate first the EWs of the SP and just stop directly if 2 or more EWs are negative.

**Comment by GPMueller** [comment]
Implemented with 82303eea3fc3d858108581e1d014da638b4e5db4.
