### ISSUE TITLE
UI: "convergence" plot

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#452]
While the idea of heaving a convergence plot for the energy or the force is in principle nice, I would remove this tab for the moment until this feature is implemented since it just causes confusion for new users when nothing is shown there.

**Comment by GPMueller** [comment]
Basic implementation on UI-ImGui with c9761e45e0e8286d6db3e4d96a22c8f61b979b15 on branch 'feature-imgui'.
Not yet working in all use cases, i.e. it still has some bugs.
