### ISSUE TITLE
Python API: set_output_folder and set_output_file_tag not working

### ISSUE THREAD

**Issue by MSallermann** [spirit-code/spirit#464]
The argtypes for both functions are incomplete.
I.e
`log.py:70     _Set_Output_File_Tag.argtypes = [ctypes.c_char_p]`
should be
`log.py:70     _Set_Output_File_Tag.argtypes = [ctypes.c_void_p, ctypes.c_char_p]`

**Comment by GPMueller** [comment]
Fixed with bddb3a4b7d74d5caa6a3c3813150aae3cef4fc88.
