### ISSUE TITLE
Error message: Tried to switch to previous image

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#465]
In my opinion, the Error message `Tried to switch to previous image` should be removed or replaced by a warning. I see the point, why it might be useful to see this message if it was triggered by the user and thus he/she should be warned, but it is also triggered in cases where the error message is misleading. For example: deleting an image triggers it (I guess to avoid that one is sitting on the last image and thus after deleting one faces a problem)

**Comment by GPMueller** [comment]
The issue when deleting an image is a bug in the API. This has been fixed with eafc8eee7bb7c9f8d5ddcc11f8d893c1121fe533.
I think in cases where the user actually made a mistake, it makes sense to give an error message, as something might not be working as expected.
