### ISSUE TITLE
BUG: Dipole-dipole interaction for more than one image

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#468]
When more than one image is used in the GUI, copying an image with dipole-dipole switched on causes bugs. The GUI claims that dipole-dipole is as well on for the new image, in fact it is not. Turning then dipole-dipole "off" will cause sooner or later a Segmentation fault (so far: when pressing start afterwards or setting a new spin configuration).

**Comment by GPMueller** [comment]
Should be fixed with the merge of PR #469.
