### ISSUE TITLE
UI: Overall position filter

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#473]
In the UI, the `overall position filter` behaves different for different coordinates:
while the `x- and z-components` are fine, the `y-components` are resetted when one switches between different images of a chain.

**Comment by SpiritSuperUser** [comment]
additionally, the default settings of the y-components differ from the ones of the other components:
- x and z are set to [-1:1]
- y is set to [1:1] in the UI, shown is however everything then

**Comment by GPMueller** [comment]
This is not always the case, so it is likely related to your geometry. Please specify the geometry you chose.

**Comment by SpiritSuperUser** [comment]
I have a hexagonal structure. The bravais vectors are given by hand:

>   1.5 -0.86602540378 0.0
  1.5  0.86602540378 0.0
  0.0 0.0 1.0

**Comment by GPMueller** [comment]
This should not happen anymore on the `feature-imgui` branch (PR #583). Since the Qt GUI is supposed to be replaced with the IMGUI being developed there, I would close this issue when the PR is merged.
