### ISSUE TITLE
UI: isosurfaces for more than one atom per unit cell

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#475]
While the feature of isosurfaces for systems with more than one atom per unit cell is in principle working, it slows down the UI drastically such that working with that feature is just not doable in a reasonable way. Maybe one should improve the visualisation to avoid that each drawn surface takes tens of seconds up to minutes. 
Additionally, qt errors are thrown:

> Qhull output at end
qhull warning: unknown flag q(71)
qhull warning: missing space after flag q(71); reserved for menu. Skipped.

**Comment by SpiritSuperUser** [comment]
apparently, this issue only shows up if the lattice geometry is 2D, ie if one calculates a lattice with 1 repetition along one of the basis vectors (for example 50x50x1). When a real 3D lattice is calculated, the speed of the visualization looks reasonable.

**Comment by GPMueller** [comment]
There is a `n_cell_step>1 && ...` missing in https://github.com/spirit-code/spirit/blob/develop/ui-cpp/src/SpinWidget.cpp#L395 which prevents the isosurface visualisation for some systems which are actually 3D.

The reason for the slow visualisation is currently unknown.

**Comment by GPMueller** [comment]
Fixed the visualisation with c1655055da4519cde5e560a4ac84b97bc15fb261 and 4c31eb925dee584b469464077aa0fc4c41f39a52.

The speed of the isosurface calculation has not been increased.
