### ISSUE TITLE
Userfriendliness: remove weird error messages when starting ui

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#480]
I think, to avoid confusion for the inexperienced user, weird error messages at the start of the GUI should be avoided. At the moment, an error message is thrown because a homogeneous transition between images 1 and 1 is attempted. I'm not sure about the purpose of these actions (creating skyrmion, remove skyrmion and create fm instead, trying to perform transition) but this should be avoided to improve userfriendliness.

**Comment by GPMueller** [comment]
This is a remnant from older versions of the UI and should indeed be removed.

**Comment by GPMueller** [comment]
Fixed with 4c31eb925dee584b469464077aa0fc4c41f39a52.
