### ISSUE TITLE
Feature Request: Add Compiler and Version to Log Output

### ISSUE THREAD

**Issue by DanielSchuerhoff** [spirit-code/spirit#488]
Feature Request: Add Compiler and Version to Log Output to ensure reproducability in terms of
- bugs
- numerical rounding
- performance

**Comment by GPMueller** [comment]
Added this with 1fb2a21d6f5341e389af887c7f2d930294d79d69 on branch `hotfix`. The log level for this is `Info`. Example output: `Compiled with: MSVC (19.12.25834.0) and nvcc (10.0) for cuda arch "sm_70"`.

This should also help a lot in cases where the CUDA backend compiles but the executable fails to run.

**Comment by GPMueller** [comment]
Merged with 5e23bf3be5aa4bacf5aae24514b0b22cbd395619 and aedc894470ae9e2c8ff73550d6bc6df26eb52a9a.
