### ISSUE TITLE
Geometry change with non-monoatomic basis

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#492]
The geometry change within the UI does not work for a basis with more than one atom. The sublattices are somehow shifted with respect to each other.
The following three images illustrate this. The goemetry is changed from 50x50 to 30x30 and back to 50x50:
![2019-02-05_07-47-22_screenshot_1](https://user-images.githubusercontent.com/28620252/52278206-7b8e5e00-2924-11e9-995f-b396e30d6161.png)
![2019-02-05_07-47-22_screenshot_2](https://user-images.githubusercontent.com/28620252/52278212-7df0b800-2924-11e9-896b-38c40cb80c1e.png)
![2019-02-05_07-47-22_screenshot_3](https://user-images.githubusercontent.com/28620252/52278216-7fba7b80-2924-11e9-9c15-2c4c2949e5b9.png)

**Comment by GPMueller** [comment]
This bug can be verified for example with [input.txt](https://github.com/spirit-code/spirit/files/2979292/input.txt), but a simpler example with only 2 basis atoms would be better.

**Comment by GPMueller** [comment]
Fixed with b947b784c89ae551a2cbfef922885cb94ea2c7bf.
