### ISSUE TITLE
defects cannot be loaded if upper case letters are used in path to file

### ISSUE THREAD

**Issue by Skyrme** [spirit-code/spirit#493]
Despite giving the correct path to the file that contains the information in input.cfg
> defects_from_file /scratch/SKYRMION__281166-WLOw/2/25/defects.txt

the defects cannot be loaded by the python api as indicated by the error messages in the log:

> [ ERROR ] [API ] [--] [--]  -----------------------------------------------------
 [ ERROR ] [API ] [--] [--]  /users/home/spirit-old/core/src/io/Configparser.cpp:386 in function 'Geometry_from_Config'
                                                 Caught exception: Failed to read Geometry parameters from file "/scratch/SKYRMION__281166-WLOw/2/25/input.cfg". Leaving values at default.
                                                 Exception backtrace:
  [ ERROR ] [API ] [--] [--]  /users/home/spirit-old/core/src/io/Dataparser.cpp:676 in function 'Defects_from_File':
                                                 Could not read defects file  "/scratch/skyrmion__281166-wlow/2/25/defects.txt"
  [ ERROR ] [API ] [--] [--]  /users/home/spirit-old/core/src/io/Filter_File_Handle.cpp:56 in function 'Filter_File_Handle':
                                                 Could not open file "/scratch/skyrmion__281166-wlow/2/25/defects.txt"
  [ ERROR ] [API ] [--] [--]  -----------------------------------------------------

**Comment by GPMueller** [comment]
I have found the corresponding bug, but it might take me some time to properly fix it.
In the meantime you can avoid this by writing the defects directly into the inputfile or using only lower capitalisation in your filenames.

**Comment by GPMueller** [comment]
Should be fixed with 6f9b4010d9c3de9f93609a8157ffd9be7e040a72.
Please let me know if this solved your problem.

**Comment by Skyrme** [comment]
This solves the problem of limitation to lower case letters. 

> 2019-02-19 17:12:44  [ INFO  ] [IO  ] [--] [--]  Reading Defects
2019-02-19 17:12:44  [ DEBUG ] [IO  ] [--] [--]  Trying to parse defects from top of file /users/home/INPUT/defects_size70_distance3.txt
2019-02-19 17:12:44  [ INFO  ] [IO  ] [--] [--]  Done reading 24 defects
