### ISSUE TITLE
Log output cannot be suppressed anymore using n_iterations_log  = 0

### ISSUE THREAD

**Issue by Skyrme** [spirit-code/spirit#494]
Should be fixed with 6f9b4010d9c3de9f93609a8157ffd9be7e040a72.
Please let me know if this solved your problem.

_Originally posted by @GPMueller in https://github.com/spirit-code/spirit/issues/493#issuecomment-464024364_

With one fix between this and the fix e82976901e22, n_iterations_log  = 0 does not suppress the output of calculation, instead the step size 1 is used. If n_iterations_log  > 0 is specified, the chosen number is used. 

> [ INFO  ] [IO  ] [--] [--]  Parameters LLG: building
[WARNING] [IO  ] [--] [--]  Keyword 'llg_output_energy_add_readability_lines' not found. Using Default: false
[WARNING] [IO  ] [--] [--]  Keyword 'llg_output_configuration_filetype' not found. Using Default: 3
[WARNING] [IO  ] [--] [--]  Keyword 'llg_max_walltime' not found. Using Default: 0
[WARNING] [IO  ] [--] [--]  Keyword 'llg_temperature_gradient_direction' not found. Using Default: 1 0 0
[WARNING] [IO  ] [--] [--]  Keyword 'llg_temperature_gradient_inclination' not found. Using Default: 0
[WARNING] [IO  ] [--] [--]  Keyword 'llg_beta' not found. Using Default: 0
[WARNING] [IO  ] [--] [--]  Keyword 'llg_stt_use_gradient' not found. Using Default: true
[ PARAM ] [IO  ] [--] [--]  Parameters LLG:
[ PARAM ] [IO  ] [--] [--]          seed              = 20006
[ PARAM ] [IO  ] [--] [--]          time step [ps]    = 0.001
[ PARAM ] [IO  ] [--] [--]          temperature [K]   = 0
[ PARAM ] [IO  ] [--] [--]          temperature gradient direction = 1 0 0
[ PARAM ] [IO  ] [--] [--]          temperature gradient inclination = 0
[ PARAM ] [IO  ] [--] [--]          damping           = 0.3
[ PARAM ] [IO  ] [--] [--]          beta              = 0
[ PARAM ] [IO  ] [--] [--]          stt use gradient  = true
[ PARAM ] [IO  ] [--] [--]          stt magnitude     = 0
[ PARAM ] [IO  ] [--] [--]          stt normal        = 1 0 0
[ PARAM ] [IO  ] [--] [--]          force convergence = 1.000000e-10
[ PARAM ] [IO  ] [--] [--]          maximum walltime  = 0
[ PARAM ] [IO  ] [--] [--]          n_iterations      = 200000000
[ PARAM ] [IO  ] [--] [--]          n_iterations_log  = 0
[ PARAM ] [IO  ] [--] [--]          output_folder     = "."
[ PARAM ] [IO  ] [--] [--]          output_any        = false
[ PARAM ] [IO  ] [--] [--]          output_initial    = false
[ PARAM ] [IO  ] [--] [--]          output_final      = true
[ PARAM ] [IO  ] [--] [--]          output_energy_step             = false
[ PARAM ] [IO  ] [--] [--]          output_energy_archive          = false
[ PARAM ] [IO  ] [--] [--]          output_energy_spin_resolved    = false
[ PARAM ] [IO  ] [--] [--]          output_energy_divide_by_nspins = false
[ PARAM ] [IO  ] [--] [--]          output_energy_add_readability_lines = false
[ PARAM ] [IO  ] [--] [--]          output_configuration_step      = false
[ PARAM ] [IO  ] [--] [--]          output_configuration_archive   = false
[ PARAM ] [IO  ] [--] [--]          output_configuration_filetype  = 3
[ INFO  ] [IO  ] [--] [--]  Parameters LLG: built
[ INFO  ] [IO  ] [--] [--]  Parameters MC: building

> [  ALL  ] [LLG ] [01] [01]  ----- LLG Calculation (VP Solver): 0:0:0.8
[  ALL  ] [LLG ] [01] [01]      Completed                    1 / 200000000 step(s) (step size 1)
[  ALL  ] [LLG ] [01] [01]      Iteration                    1 / 200000000
[  ALL  ] [LLG ] [01] [01]      Time since last step:        0:0:0.8
[  ALL  ] [LLG ] [01] [01]      Iterations / sec:            112.451
[  ALL  ] [LLG ] [01] [01]      Force convergence parameter: 0.000000000100
[  ALL  ] [LLG ] [01] [01]      Maximum force component:     0.100507441312

**Comment by GPMueller** [comment]
Should be fixed with 32883d7d1e15c64d7390099cab1f4633c057ec82.
`n_iterations_log <= 0` will mean the same as `n_iterations_log = n_iterations` and `n_iterations` now cannot be less than `1`.
