### ISSUE TITLE
The colour scheme

### ISSUE THREAD

**Issue by Hubin-Luo** [spirit-code/spirit#508]
The spin arrows are by default coloured according to the Cartesian axes, i.e., +z is white and -z is black, etc. Is there any way to change the colour scheme? For example, I may want to set [111] to be white and -[111] to be black.

**Comment by GPMueller** [comment]
With 218b5f5196614eb73c4db7601b1f71956359afef, I have added the following settings for the colour map: <img width="250" alt="Screen Shot 2019-03-22 at 15 05 34" src="https://user-images.githubusercontent.com/20167491/54828226-03051600-4cb4-11e9-9f42-98792d090c19.png">

The shown axis changes the map for a regular skyrmion from 
![2019-03-22_15-04-19_Screenshot_1](https://user-images.githubusercontent.com/20167491/54828323-33e54b00-4cb4-11e9-89ba-53ac38e78a52.png)
to
![2019-03-22_15-04-19_Screenshot_2](https://user-images.githubusercontent.com/20167491/54828329-3778d200-4cb4-11e9-828f-48eaff11dda9.png)
