### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by code-whale** [spirit-code/spirit#578]
Hello, I want to learn how to use spirit, but I don't know how to build this software. I hope to simulate directly in GUI. I try to build software in OSX according to your tutorial, but the following error occurred. Can you help me?
<img width="570" alt="截屏2020-11-04 上午11 42 49" src="https://user-images.githubusercontent.com/61874432/98066752-defb4600-1e92-11eb-9064-534ef99d603d.png">

**Comment by MSallermann** [comment]
Hi,

it looks like you either have no installation of cmake or it is not in your shell path. If you fix that, the error should disappear. You can download cmake binaries here https://cmake.org/download/ or install it via homebrew.

Best,
Moritz

**Comment by code-whale** [comment]
@MSallermann ,Thank you for your reply! I successfully installed cmake using ````brew Install cmake````, but when I continued the build, the error as shown in the figure below occurred. Is this because I did not have read permissions and did not install QT5? Please tell me how to solve this error. Thanks again for your help!
![image](https://user-images.githubusercontent.com/61874432/98091151-f56bc680-1ebf-11eb-8529-c3950a4bae17.png)

**Comment by MSallermann** [comment]
The first issue seems to be connected to write permissions. I have not seen this before, make sure you have write and read permissions for these files (or try to run cmake as sudo).

The second error is due to cmake not finding QT. 
If you want to use the GUI, you need to install QT first. And if the error persists, you can uncomment this line in the CMakeLists file`# set( USER_PATH_QT       "~/QT/5.7" )` and edit the path so that it points to your QT install location.
If you want to just test the rest of the compilation you can run cmake with the additonal argument `-DSPIRIT_UI_CXX_USE_QT=OFF`. This will compile spirit without the GUI and does not not require QT.

**Comment by code-whale** [comment]
@MSallermann ,I would like to ask you how to install Qt. I am now downloading from https://www.qt.io/download. Is that right?
![image](https://user-images.githubusercontent.com/61874432/98098106-dde50b80-1ec8-11eb-85f6-085f18813989.png)

**Comment by code-whale** [comment]
@MSallermann ，I am very sorry to bother you. After I tried to install QT5, I reported an error as shown in the figure below. I have little knowledge of building code, I don't know what caused the error, I really hope to use GUI for simulation
![image](https://user-images.githubusercontent.com/61874432/98100627-189c7300-1ecc-11eb-8ff2-e6650c08e4e5.png)

**Comment by MSallermann** [comment]
Hmm seems like you are missing libicui. You could try to install it with `brew install icu4c`.

**Comment by code-whale** [comment]
@MSallermann ，I ran ````brew install icu4c````, but the same error occurred in the last problem. I would like to ask how you installed Qt. I think my Qt installation is wrong, thank you for your patient help!

**Comment by code-whale** [comment]
@MSallermann ,I seem to have successfully compiled Spirit after changing path again, as shown in the figure below. Is this successful? (I'm not sure), I would like to ask you how to launch the GUI interface? No ICONS are generated after compilation...
![image](https://user-images.githubusercontent.com/61874432/98126149-3aa7ec80-1ef0-11eb-8127-93b4193fd9a7.png)

**Comment by code-whale** [comment]
Sorry for my own negligence, I saw that the Spirit executable has been generated! I will start learning Spirit! Thank you for your patient help!

**Comment by MSallermann** [comment]
Nice, that it works for you now!
