### ISSUE TITLE
Dipole-Dipole interaction test failing while using CUDA

### ISSUE THREAD

**Issue by sumeetkd** [spirit-code/spirit#584]
./ctest.sh runs without errors when running *without* the CUDA backend installed.
After installing the CUDA backend, the test Dipole-Dipole Interaction in test_physics.cpp fails with the following message

Failed DDI-Gradient comparison at i = 0
  Gradient (FFT):
   0.0143112
  0.00954871
   0.0188101
  Gradient (Direct):
  0.00858198
  0.00976415
   0.0160611

The log file for the failed test is [LastTest_with_CUDA_2.1.1.log](https://github.com/spirit-code/spirit/files/5808006/LastTest_with_CUDA_2.1.1.log)

**Comment by MSallermann** [comment]
Hi, thank you for reporting this! I have pushed a fix to the develop branch https://github.com/spirit-code/spirit/commit/c97f00b6bcfad1161c0583f491366013a56b0e80. Can you check it out and see if the problem persists?

**Comment by sumeetkd** [comment]
./ctest.sh runs without errors now.
Thanks for the quick resolution.
