### ISSUE TITLE
Geometry definition 

### ISSUE THREAD

**Issue by zangyuzhe** [spirit-code/spirit#592]
Hi, I found there is no geometry configuration option in the spirit? Is it possible to define a disk and the corrospond interactions in a disk as well?

**Comment by GPMueller** [comment]
You can find the available geometry configuration options in [the geometry input documentation](https://spirit-docs.readthedocs.io/en/latest/core/docs/Input.html#geometry-a-name-geometry-a). You _can_ specify the disk you want to simulate manually, as a single large unit cell (if you do so, I would recommend to script this).

Alternatively, you can build with support for defects (the `SPIRIT_ENABLE_DEFECTS` cmake option) and set all the atoms outside a given radius to atom-type -1 (vacancies), using this API function: [`void Configuration_Set_Atom_Type(State *state, int type, const float position[3]=defaultPos, const float r_cut_rectangular[3]=defaultRect, float r_cut_cylindrical=-1, float r_cut_spherical=-1, bool inverted=false, int idx_image=-1, int idx_chain=-1)`](https://spirit-docs.readthedocs.io/en/latest/core/docs/c-api/Configurations.html#configuration-set-atom-type).
See also [the defects input documentation](https://spirit-docs.readthedocs.io/en/latest/core/docs/Input.html#disorder-and-defects-a-name-defects-a).

**Comment by GPMueller** [comment]
Dear @zangyuzhe do you have any follow-up questions or can we close this issue?

**Comment by zangyuzhe** [comment]
Dear @GPMueller,

Thank you for your reply,  it answears my question perfectly. I don't have any further question.
