### ISSUE TITLE
Per spin position and anisotropy properties

### ISSUE THREAD

**Issue by stricot** [spirit-code/spirit#593]
Hi all,

First thanks for sharing this very nice code. 
For my needs, I'd like to be able to define different anisotropy properties (for example easy axis direction and anisotropy constant) for each spin. I understood that we can define these properties for each spin of the unit cell, but i would need to define for each spin of the whole system.
I guess this would imply to be able to define a system where we can tell the position of each spin (without defining a Bravais lattice), or to be able to define a cubic unit cell with many spins inside

* Is it technically possible ?
* Would it still be possible to use the periodicity ?

Thanks

**Comment by GPMueller** [comment]
I'm afraid there is currently no easier way than to create a single unit cell, containing all the spins you wish to simulate. You can then specify the anisotropies for all the spins individually. Periodical boundary conditions will still work, but the drawbacks are:
- more complicated input
- I think the API does not support this this scenario properly
- parallelisation is over unit cells, not spins, so openmp or cuda will likely run in serial in your case

**Comment by GPMueller** [comment]
Dear @msspec do you have any follow-up questions or can we close this issue?

**Comment by stricot** [comment]
Dear @GPMueller ,

Sorry not to have answered earlier. Thanks for your reply, perhaps I will try to implement such a geometry for testing purposes (since it would lead to performance issues as you wrote). Thanks again, you can close the issue.
