### ISSUE TITLE
Weird results caused by using CUDA

### ISSUE THREAD

**Issue by zangyuzhe** [spirit-code/spirit#596]
Hi,

I found some weird results caused by using CUDA. Log file, cfg file, initial state and final state are attached.

I can’t relax a skyrmion even under 100T external field with the attached cfg file. When using CUDA, some spins in the centre are pinned and can’t be flipped. But this doesn’t happen if I use pip version of spirit. 

Can anyone help me sort this out?

Many thanks,
Yuzhe

System information:
- Os: Ubuntu 20.10
- Kernal: 5.8.0-53-generic
- CPU: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
- GPU: GeForce GTX 1050
- nvcc: Cuda compilation tools, release 10.1, V10.1.243
- gcc: 9.3.0
- cmake: 3.16.3

![skyrmion_state](https://user-images.githubusercontent.com/43541543/118682170-19f21500-b7f8-11eb-8ae5-66c4154b31ca.png)
![FInal_state](https://user-images.githubusercontent.com/43541543/118682182-1e1e3280-b7f8-11eb-814d-fa258f68b5b7.png)
[Log_2021-05-09_11-04-41.txt](https://github.com/spirit-code/spirit/files/6502575/Log_2021-05-09_11-04-41.txt)
[input_modified.cfg.txt](https://github.com/spirit-code/spirit/files/6502578/input_modified.cfg.txt)
[2021-05-09_11-05-42_Image-00_Spins-final.ovf.txt](https://github.com/spirit-code/spirit/files/6502583/2021-05-09_11-05-42_Image-00_Spins-final.ovf.txt)

**Comment by GPMueller** [comment]
There might be an issue with the multi-atom basis, this looks like a bug. With the CUDA version it can always be due to the lack of precision (the CUDA backend is limited to single precision `float`). However, your log indicates that the pairs were correctly identified,
```
2021-05-09 11:04:41  [ PARAM ] [IO  ] [--] [--]  Done reading 50 spin pairs from file "input/input_modified.cfg", giving 10 exchange and 10 DM (symmetry-reduced) pairs.
```
(at least I get the same on my machine).

I suspect that these stripes will appear throughout the whole system if you start from a random configuration? It might be an issue with the dipolar interactions, please try switching them off (`ddi_method none`) and see if the issue persists. If not, we seem to have a bug in the cuFFT implementation of the DDI.

**Comment by zangyuzhe** [comment]
I have done a quick test which started from a random configuration.
This is the result with DDI.
![WIth_DDI](https://user-images.githubusercontent.com/43541543/118709675-32245d00-b815-11eb-9a90-83da28a41a36.png)

This is the result without DDI.
![Without_DDI](https://user-images.githubusercontent.com/43541543/118709715-3ea8b580-b815-11eb-8e8f-65ac83ae3543.png)

**Comment by GPMueller** [comment]
Looks to me like the bugfix from commit 3e46c0daee624abf042117ae87a779ff6e979704 was not applied to the CUDA backend, leading to indexing errors when using a multi-atom basis.

**Comment by MSallermann** [comment]
Dear @zangyuzhe, thank you for pointing out these issues! There were indeed several bugs in the cuda backend with regard to multi-atom bases. I have pushed fixes to the develop branch 382cac3c7e9176db707512afbdbaa1e189b9384b. According to my checks, the issues you encountered should be fixed now. Please let us know if you find more problems!

**Comment by zangyuzhe** [comment]
Dear @MSallermann , I will run some test simulation today. If there is any problem, I will let u know.

**Comment by GPMueller** [comment]
Dear @zangyuzhe, is your problem solved so we could close this issue?

**Comment by zangyuzhe** [comment]
Dear @GPMueller , thank you for ur help. Problem has been resolved.
