### ISSUE TITLE
Spin Torque GUI

### ISSUE THREAD

**Issue by orig21-94** [spirit-code/spirit#610]
Hello,

What are the units of "Spin Torque" (Gradient Method) in the "Parameters" tab of the Spirit GUI?

Is it meV just like K, J and D or arbitrary?

I saw that there is an other similar open issue about STT but i didn't find any answer on that matter.

Many thanks!

**Comment by GPMueller** [comment]
Please refer to https://github.com/spirit-code/spirit/issues/607#issuecomment-1030071256, as SOT and STT are both covered by the same implementation.
