### ISSUE TITLE
Query regarding Monte Carlo method

### ISSUE THREAD

**Issue by Sayan611** [spirit-code/spirit#619]
Dear Spirit users and developers,

I want to know how should I choose my cell size ( 'n_basis_cells' ) in my 'input.cfg' file to find the ground state of my system by performing the Monte Carlo method.

In my case, I am using 'heisenberg_neighbours' hamiltonian, and the interaction terms are specified in a separate file with 1776 atom pairs of a monolayer (2D).

For cell size- 50X50X1: I am getting a ferromagnet.                     
                     100X100X1: I am getting a canted spin spiral like structure (the first figure)                   
                     200X200X1: I am getting a different one (the second figure). 
when I am performing Monte Carlo. I have attached the results.

I will be very grateful if you kindly tell me the right way to proceed to get the ground state by Monte Carlo in this case and if you kindly comment on the choice of acceptance ratio.

Thank you.

Regards
Sayan Banik

![For 100X100X1](https://user-images.githubusercontent.com/88526735/167261547-1e61dd4d-a805-41b5-82c7-baee742c3121.jpg)
![For-200X200X1](https://user-images.githubusercontent.com/88526735/167261629-e21d159c-b155-4810-b769-f55ab41ed4e3.jpeg)

**Comment by GPMueller** [comment]
Dear @Sayan611, please attach your input files and a log of the initialisation phase (the latter will contain information about how the input was processed and how many interaction pairs were determined etc.

Please also read through the input file documentation and make sure your input corresponds to what you want to achieve: https://spirit-docs.readthedocs.io/en/latest/core/docs/Input.html#heisenberg-hamiltonian-a-name-heisenberg-a

 - `n_basis_cells` is the number of atoms in the basis cell of your lattice, it's not really related to the approach to find the ground state
 - if you specified `heisenberg_neighbours`, no interaction pairs will be read in

Regarding the acceptance-ratio, there's no generic advice I could give you. Instead, I'd recommend that you read up on the Metropolis Monte Carlo algorithm and its alternatives, and take a look at our implementation, which uses adaptive cone sampling: https://github.com/spirit-code/spirit/blob/master/core/src/engine/Method_MC.cpp#L68-L192

You can find a basic introduction to our Monte Carlo implementation and some references in [our paper about Spirit](https://arxiv.org/abs/1901.11350).

**Comment by Sayan611** [comment]
Dear @GPMueller, thank you for your help. I have got my points from the references you gave.

**Comment by GPMueller** [comment]
@Sayan611 do you have any follow-up questions?
If not, please close the issue.
