### ISSUE TITLE
Query regarding creation of skyrmion lattice

### ISSUE THREAD

**Issue by Sayan611** [spirit-code/spirit#622]
Dear SPIRIT developers,
I can create a single skyrmion in the middle of a 32x32x1 lattice in the SPIRIT interface. Can I make a skyrmion lattice here? I want to know how to copy one localised state from one point and paste it into a different point in my 32x32x1 lattice.
I would be grateful if you kindly help me out in this matter.
Thank you.

Regards
Sayan Banik

**Comment by GPMueller** [comment]
If you want to do this by hand in the desktop app, this is only briefly hinted at in the [desktop GUI docs](https://spirit-docs.readthedocs.io/en/latest/docs/UI-Qt.html)

> Additional features
> -------------------------
>
>  -  Drag mode: drag, copy, insert, change radius

This "drag mode" is activated with `F5`:
 - left-click to copy
 - right-click to paste
 - hold left-click to drag something around
 - `ctrl`+scroll to change the radius

Note that you can automate the creation of skyrmion lattices with a Python script using [`spirit.configuration`](https://spirit-docs.readthedocs.io/en/latest/core/docs/python-api/spirit.configuration.html)

**Comment by Sayan611** [comment]
Thank you @GPMueller. It helped.
