### ISSUE TITLE
Queries Regarding SPIRIT Monte Carlo

### ISSUE THREAD

**Issue by Sayan611** [spirit-code/spirit#623]
Dear Developers,
This is regarding some queries and clarification for the Monte Carlo (MC) method used in SPIRIT. I have the following queries,

1) In the mc.py file I do not understand the functionality of  "n_thermalisation", "n_decorrelation", and "n_samples" tags. It seems that "n_thermalisation"  and "n_samples" tags are related to the number of iterations of MC, but then does it take the "mc_n_iterations" value from the input.cfg file mentioned in mc.py?

2) The "n_temperatures", "T_start", and "T_end"  in the mc.py file mean the annealing process, which starts from "T_end" and reaches "T_start" in the "n_temperatures" steps. Am I correct?

3) How do I modify mc.py to use an initial spin configuration chain from a previously saved file as the starting spin configuration for MC and save the final spin configuration after the MC has finished? Like the one I do by loading the spin configuration chain, starting the MC, and saving the spin configuration chain when MC is completed in GUI. 

I would be very much grateful if you kindly help me in these matters.
Thank you.

Regards
Sayan Banik

**Comment by GPMueller** [comment]
Dear @Sayan611, please check [our paper about Spirit](https://arxiv.org/abs/1901.11350). There's a section on Monte Carlo and Fig. 4 mentions the thermalisation performed at each temperature step. It's an important component of proper Monte Carlo simulations.

Performing _correct_ Monte Carlo simulations can be a bit tricky. I believe you'll need to understand the scripts you're using to a degree, where the meaning of `n_temperatures` etc. should be clear to you from the Python code. Please use the provided scripts only as a starting point, not as a fully finished setup.

Regarding your third question, see [the docs](https://spirit-docs.readthedocs.io/en/latest/core/docs/python-api/spirit.io.html) and

https://github.com/spirit-code/spirit/blob/14ed7782bd23f4828bf23ab8136ae31a21037bb3/ui-python/gneb.py#L32-L36

----------------------------------

A final note: while I don't know the scope or goals of your project, I want to note that if your goal is to do thorough and correct simulations it might be a good idea to read up on the available literature a bit. The papers we referenced should be a decent starting point, but I'll give some suggestions:
- A very detailed description of Monte Carlo methods can be found in M. E. J. Newman and G. T. Barkema. Monte Carlo Methods in Statistical Physics. Oxford University Press, Oxford, New York, Feb. 1999.
- U. Nowak. Thermally Activated Reversal in Magnetic Nanostructures, volume IX of Annual Reviews of Computational Physics. Singapore: World Scientific, p 105, ed d stauffer edition, 2001.
- D. P. Landau and K. Binder. A Guide to Monte Carlo Simulations in Statistical Physics, Sept. 2009. doi:10.1017/CBO9780511994944.
- D. Hinzke and U. Nowak. Monte Carlo simulation of magnetization switching in a Heisenberg model for small ferromagnetic particles. Computer Physics Communications, 121-122:334–337, Sept. 1999. doi:10.1016/S0010-4655(99)00348-3.

**Comment by Sayan611** [comment]
Dear @GPMueller thank you very much for your help. I will surely go through the references you mentioned.
