### ISSUE TITLE
Simulating Skyrmions (Python API)

### ISSUE THREAD

**Issue by bufay** [spirit-code/spirit#633]
Hi,everyone!
   I  use VASP package to caculate the calculate the magnetic parameters , and  divided the calculated magnetic moment of the magnetic atom by 2 as  $\mathop{S}\limits^{\rightarrow}$ , which was also set as the $\mu_s$ parameter in input.cfg. Similarly, $J_1$, $J_2$ , $J_3$ , $K_{ani}$, $D_{dmi}$ were also divided by $S^2$.
      

$$
H = \sum_{i , j} J_{1}(\mathop{S_{i}}\limits^{\rightarrow} \cdot \mathop{S_j}\limits^{\rightarrow}) +\sum_{i , k} J_{2}(\mathop{S_{i}}\limits^{\rightarrow} \cdot \mathop{S_k}\limits^{\rightarrow}) + \sum_{i , l} J_{3}(\mathop{S_{i}}\limits^{\rightarrow} \cdot \mathop{S_l}\limits^{\rightarrow}) + \sum_{i , j} \mathop{d_{ij}}\limits^{\rightarrow} \cdot (\mathop{S_i}\limits^{\rightarrow} \times \mathop{S_j}\limits^{\rightarrow}) + \sum_{i} K(S_i^z)^{2}
$$

   I inputted these parameters to simulate the Skyrmions by the lllg-heun method in python package, but the  Skyrmions displayed were elliptical. Different from the circular  Skyrmions in other people's literature, I want to know if there is something wrong with my input file, Thank you
[inut.txt](https://github.com/spirit-code/spirit/files/11154957/inut.txt

**Comment by bufay** [comment]
Can someone give me some advice ? Thank you!

**Comment by MSallermann** [comment]
Hey, how did you determine the Skyrmions to be elliptical?

I have used your inputfile in the Spirit GUI and the Skyrmions, after energy minimization, seem to be circular:
![2023-04-11_17-13-38_Screenshot_1](https://user-images.githubusercontent.com/36901117/231209267-5d9873dd-40d3-4c47-96c0-4f6896f9567c.png)

**Comment by bufay** [comment]
thanks ,you're right
