### ISSUE TITLE
UI-QT/VFRendering: Add Black and White colormaps

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#65]
I mean only black and only white, independent of orientation.
This would be useful for small spin systems which one wants to visualise without a colormap.

**Comment by FlorianRhiem** [comment]
These colormaps were added in [VFRendering 0.4.0](https://github.com/FlorianRhiem/VFRendering/releases/tag/v0.4.0). Previously, the default colormap already was a uniform white, but there was no uniform black colormap.

**Comment by GPMueller** [comment]
Added to UI-QT in 309793d0285a45845f34552cab46616854c89aee
