### ISSUE TITLE
UI-QT: Add checkbox for 3D shadow effect on (iso)surfaces

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#81]
This would be a very nice addition, as some isosurfaces are currently hard to see properly without 3D effects. Example:
![isosurf_no3d](https://cloud.githubusercontent.com/assets/20167491/22332529/a8105b1c-e3d1-11e6-84ac-620014030268.png)
Note that shadows may distort colormaps which include a black-white transition component (e.g. the HSV map).

**Comment by FlorianRhiem** [comment]
As of version 0.5.0, VFRendering supports this using the `IsosurfaceRenderer::Option::LIGHTING_IMPLEMENTATION`. You could try something like:

```
float lighting(vec3 position, vec3 normal) {
    return abs(normal.z);
}
```

When using a regular grid, providing your own tetrahedron indices to the Geometry class will strongly improve the visual quality, as QHull tends to produce near zero volume tetrahedra. These lead to undefined normals and cause discontinuities among neighboring triangles, leading to effects like this:
![image](https://cloud.githubusercontent.com/assets/4411847/22370079/ca137ae6-e48f-11e6-9634-aac1cd2488ec.png)

For non-regular grids or regular grids with user-provided tetrahedron indices, the surfaces should appear smooth.

**Comment by GPMueller** [comment]
Updated VFRendering in 042f4a67d26ae963a4f9a135fe087474d8dff829
Added shadow option to UI-QT in 309793d0285a45845f34552cab46616854c89aee

**Comment by FlorianRhiem** [comment]
VFRendering version 0.5.2 has improved the calculation of isosurface normals.
