### ISSUE TITLE
VFRendering: bounding box needs indicator for periodical boundary conditions

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#82]
dotted lines to indicate periodicity in a direction would do the trick

**Comment by FlorianRhiem** [comment]
This feature was added in VFRendering 0.6.0, by adding an optional parameter to the `BoundingBoxRenderer` constructor or two optional parameters to the factory methods like `forCuboid()`. The demo shows how these parameters can be used to add dashed pbc indicators.

**Comment by GPMueller** [comment]
Implemented in 6b216ffd8c0d08fb6165d85f606b129654578be6
