### ISSUE TITLE
UI-QT: camera control is inconvenient

### ISSUE THREAD

**Issue by n-s-kiselev** [spirit-code/spirit#92]
* key control: rotation is needed
* add x,y,z keys for camera settings - shift+key should project to other side
* mouse control: rotation is inconvenient, zoom step size is too small - alternatively add key control with smaller step size
* camera: should be able to smoothly change FOV

**Comment by GPMueller** [comment]
In b5250741aafa92cdbeec4da247238069ddd29e66:
- Added key controls for rotation and movement (including shift for smaller steps), see F1 for keybindings.
- Added shift for smaller steps in zoom (mouse)

**Comment by GPMueller** [comment]
In 6f1c5a16ccb18c272c048615c70401c9aed772c7:
- Added x,y,z keys for camera control (shift to invert)
- Added FOV settings

**Comment by GPMueller** [comment]
Added more convenient "bounded" camera in 59ed8f8eda06ccedff2a48be98abfcede4611f5b
